"""Hand-audit of the teacher's risk-factor labels -- the measured version of "spot-checked by hand".

    python -m src.labels.audit sample     # draw a review sheet (deterministic, seeded)
    python -m src.labels.audit review     # fill it in, one risk at a time
    python -m src.labels.audit score      # agreement rates with clustered CIs

Numeric labels come from XBRL and need no audit: they are exact by construction and already checked
against the excerpt by `check_grounding`. Risk-factor labels are the opposite -- generated by Claude
Haiku, unverifiable from the data itself, and scored by src/eval/metrics.py as if they were truth.
Every risk-factor number this project reports is therefore conditional on the teacher being right,
and that conditional is untested until a human reads the filings.

Three verdicts per sampled risk, because they fail differently and the fixes differ:

  grounded    Is this risk actually stated in the text the teacher was given? A "no" is a
              hallucinated label -- it teaches the student to invent risks, and it is the one
              failure that makes the training data actively harmful rather than merely noisy.
  category    Would a human pick the same category? This is what `category_f1` and
              `category_accuracy` score, so it is the headline agreement number.
  summary     Is the summary faithful to the filing and specific to this company, rather than
              boilerplate that would fit any registrant?

Two design choices worth defending:

**The reviewer picks the category before seeing the teacher's.** Showing a label and asking "do you
agree?" measures agreement with an anchor, not independent agreement -- the reviewer accepts a
plausible-looking answer they would not have produced. `review` hides the teacher's category, takes
the human's, then compares programmatically. Grounding and summary verdicts necessarily show the
teacher's text, so only the category verdict gets this treatment; it is also the only one used as
the headline.

**The sample is clustered by filing, and so is the interval.** A uniform draw of 50 risks would land
in ~50 distinct filings, each demanding its own read of Item 1A -- hours of work for one number. So
`sample` draws filings first, then risks within them. That makes the items non-independent (one
misread section corrupts every risk under it), and `score` accordingly resamples *filings* in the
bootstrap, exactly as src/eval/metrics.py does. Treating 50 clustered items as 50 independent ones
would report an interval that is too narrow.

The completed sheet lives in docs/audit/ and is checked in. It is evidence for a claim the README
makes; a number without the worksheet behind it is the thing this file exists to replace.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from src.eval.metrics import BOOTSTRAP_CONFIDENCE, ConfidenceInterval, _percentile
from src.labels.schema import RISK_CATEGORIES, ExtractionTarget, RiskFactor

ROOT = Path(__file__).resolve().parents[2]
PROCESSED_DIR = ROOT / "data" / "processed"
AUDIT_DIR = ROOT / "docs" / "audit"

SHEET_PATH = AUDIT_DIR / "teacher_audit.jsonl"
FILINGS_PATH = AUDIT_DIR / "teacher_audit_filings.jsonl"
META_PATH = AUDIT_DIR / "teacher_audit_meta.json"

SPLITS = ("train", "val", "test")

# 12 filings x 4 risks ~= 48 items, against ~13 risks/filing. Enough to distinguish "the teacher is
# broadly right" from "the teacher is wrong a third of the time"; not enough to resolve two points
# of difference, which is why score reports an interval and not just a rate.
DEFAULT_FILINGS = 12
DEFAULT_PER_FILING = 4
DEFAULT_SEED = 0

# Two strata, scored separately and never pooled.
#
# The `random` stratum is a uniform draw over the whole corpus, so its rate is an unbiased estimate
# of label quality across the dataset -- that is the number the README's "spot-checked" claim needs.
#
# But the test split is 12 of 216 filings, so a uniform draw of 12 is expected to contain fewer than
# one of them, and this one contained zero. Test gold labels are what src/eval/metrics.py scores
# every reported risk-factor number against: if they are wrong, the headline result is wrong in a
# way no amount of corpus-wide quality can rescue. So the `test` stratum oversamples them
# deliberately. Pooling the two would bias the corpus estimate toward whatever the test split
# happens to look like, which is why `score` reports them apart.
DEFAULT_TEST_FILINGS = 3
STRATA = ("random", "test")

# A cluster bootstrap estimates between-filing variance by redrawing filings. With one filing every
# resample is identical, so the interval collapses to a point -- a partially-reviewed sheet would
# report "95% CI [100.0%, 100.0%]" off four items. That is worse than no interval, so below this
# many reviewed filings the CI is withheld and the report says why.
MIN_CLUSTERS_FOR_CI = 3
BOOTSTRAP_RESAMPLES = 10_000

RISK_SECTION_MARKER = "## Item 1A. Risk Factors"


# ------------------------------------------------------------------------------------------------
# Loading the labeled corpus
# ------------------------------------------------------------------------------------------------


@dataclass
class LabeledFiling:
    """One dataset row, unpacked into the two things an audit needs: what the teacher saw, and what
    it produced."""

    ticker: str
    accession_no: str
    split: str
    risk_text: str
    risks: list[RiskFactor]

    @property
    def risk_digest(self) -> str:
        """Fingerprint of the exact labels under audit.

        A verdict is about a specific sentence the teacher wrote. Rebuilding the dataset with a
        different excerpt budget or a re-run teacher produces different sentences at the same index,
        and silently re-pointing old verdicts at new labels would turn the worksheet into fiction.
        `score` compares this digest and refuses stale rows -- the same reasoning as the teacher
        cache key in src/labels/build.py.
        """
        payload = json.dumps([r.model_dump() for r in self.risks], sort_keys=True)
        return hashlib.sha256(payload.encode()).hexdigest()[:12]


def risk_section_of(excerpt: str) -> str:
    """The Item 1A slice of an excerpt -- the exact text the teacher was given.

    Duplicated deliberately from src/labels/build.py rather than imported: this module must show the
    reviewer what was actually labeled, and a shared helper that later changes its slicing would
    silently change what "the teacher saw" means for verdicts already recorded.
    """
    idx = excerpt.find(RISK_SECTION_MARKER)
    return excerpt[idx:] if idx != -1 else ""


def load_labeled_filings(processed_dir: Path = PROCESSED_DIR) -> list[LabeledFiling]:
    """Every labeled filing across all three splits, in a stable order.

    Filings whose Item 1A is incorporated by reference are excluded: they carry an empty risk list
    by design, so there is nothing to audit and including them would inflate the denominator with
    guaranteed-correct emptiness.
    """
    out: list[LabeledFiling] = []
    for split in SPLITS:
        path = processed_dir / f"{split}.jsonl"
        if not path.exists():
            continue
        for line in path.read_text().splitlines():
            if not line.strip():
                continue
            row = json.loads(line)
            if row.get("risk_factors_by_reference"):
                continue
            target = ExtractionTarget.model_validate_json(row["messages"][-1]["content"])
            if not target.risk_factors:
                continue
            out.append(
                LabeledFiling(
                    ticker=row["ticker"],
                    accession_no=row["accession_no"],
                    split=split,
                    risk_text=risk_section_of(row["messages"][1]["content"]),
                    risks=target.risk_factors,
                )
            )
    out.sort(key=lambda f: f.accession_no)
    return out


# ------------------------------------------------------------------------------------------------
# Sampling
# ------------------------------------------------------------------------------------------------


def draw_sample(
    filings: list[LabeledFiling],
    n_filings: int = DEFAULT_FILINGS,
    per_filing: int = DEFAULT_PER_FILING,
    seed: int = DEFAULT_SEED,
    test_filings: int = DEFAULT_TEST_FILINGS,
) -> tuple[list[dict], list[dict]]:
    """Two-stage cluster sample: filings without replacement, then risks within each.

    Returns (risk rows, filing rows). Risks within a filing are drawn at random rather than taking
    the first N: a teacher writing a list tends to put the obvious risks first, so the head of the
    list is systematically easier than the tail.

    The `test` stratum is drawn from filings the random stratum did not already take, so no filing
    is reviewed twice and no verdict is counted in both strata.
    """
    if not filings:
        raise SystemExit(
            f"No labeled filings found in {PROCESSED_DIR}. Run `python -m src.labels.build` first."
        )

    rng = random.Random(seed)
    chosen = rng.sample(filings, k=min(n_filings, len(filings)))
    strata = {f.accession_no: "random" for f in chosen}

    if test_filings:
        remaining = [f for f in filings if f.split == "test" and f.accession_no not in strata]
        extra = rng.sample(remaining, k=min(test_filings, len(remaining)))
        chosen += extra
        strata.update({f.accession_no: "test" for f in extra})

    chosen.sort(key=lambda f: (strata[f.accession_no], f.accession_no))

    risk_rows: list[dict] = []
    filing_rows: list[dict] = []
    for filing in chosen:
        stratum = strata[filing.accession_no]
        indices = sorted(rng.sample(range(len(filing.risks)), k=min(per_filing, len(filing.risks))))
        for i in indices:
            risk = filing.risks[i]
            risk_rows.append(
                {
                    "id": f"{filing.accession_no}#{i}",
                    "ticker": filing.ticker,
                    "accession_no": filing.accession_no,
                    "split": filing.split,
                    "stratum": stratum,
                    "risk_index": i,
                    "risk_digest": filing.risk_digest,
                    "teacher_title": risk.title,
                    "teacher_category": risk.category,
                    "teacher_summary": risk.summary,
                    # Filled by `review`. null means "not yet reviewed" -- distinct from false.
                    "human_category": None,
                    "grounded": None,
                    "summary_ok": None,
                    "note": "",
                }
            )
        filing_rows.append(
            {
                "accession_no": filing.accession_no,
                "ticker": filing.ticker,
                "split": filing.split,
                "stratum": stratum,
                "risk_digest": filing.risk_digest,
                "n_teacher_risks": len(filing.risks),
                "n_sampled": len(indices),
                # Recall, which per-risk precision cannot see: risks the filing discloses and the
                # teacher never emitted. Nearly free to collect -- the reviewer has just read the
                # whole section for the precision items anyway.
                "missed_risks": None,
                "note": "",
            }
        )
    return risk_rows, filing_rows


def write_sheet(risk_rows: list[dict], filing_rows: list[dict], meta: dict) -> None:
    AUDIT_DIR.mkdir(parents=True, exist_ok=True)
    _write_jsonl(SHEET_PATH, risk_rows)
    _write_jsonl(FILINGS_PATH, filing_rows)
    META_PATH.write_text(json.dumps(meta, indent=2) + "\n")


def _write_jsonl(path: Path, rows: list[dict]) -> None:
    with path.open("w") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")


def _read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        raise SystemExit(f"{path} not found. Run `python -m src.labels.audit sample` first.")
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


# ------------------------------------------------------------------------------------------------
# Scoring
# ------------------------------------------------------------------------------------------------


@dataclass
class AuditReport:
    stratum: Optional[str]
    n_reviewed: int
    n_total: int
    n_filings: int
    category_agreement: Optional[float]
    grounded_rate: Optional[float]
    summary_ok_rate: Optional[float]
    # (teacher category, human category) -> count, for disagreements only.
    confusions: dict[tuple[str, str], int] = field(default_factory=dict)
    missed_risks: Optional[int] = None
    teacher_risks_in_read_filings: int = 0
    cis: dict[str, ConfidenceInterval] = field(default_factory=dict)
    stale: list[str] = field(default_factory=list)

    @property
    def implied_recall(self) -> Optional[float]:
        """Teacher risks / (teacher risks + risks it missed), over fully-read filings.

        An upper bound on the teacher's true recall: a human reading Item 1A once catches omissions
        the teacher made loudly, not every risk buried in a subordinate clause.
        """
        if self.missed_risks is None or not self.teacher_risks_in_read_filings:
            return None
        total = self.teacher_risks_in_read_filings + self.missed_risks
        return self.teacher_risks_in_read_filings / total if total else None


def _rate(values: list[bool]) -> Optional[float]:
    return sum(values) / len(values) if values else None


def score_sheet(
    risk_rows: list[dict],
    filing_rows: list[dict],
    filings: Optional[list[LabeledFiling]] = None,
    n_resamples: int = BOOTSTRAP_RESAMPLES,
    seed: int = DEFAULT_SEED,
    stratum: Optional[str] = None,
) -> AuditReport:
    """Agreement rates over the reviewed rows, with filing-clustered bootstrap intervals.

    `stratum` restricts scoring to one stratum; `None` scores every row, which is only meaningful
    for a sheet drawn without oversampling (see STRATA on why the two are not pooled).

    Unreviewed rows are excluded rather than counted as agreement. A half-finished sheet should
    report a wide interval over what was actually checked, not a rate diluted toward whatever the
    unchecked rows would have been.
    """
    if stratum is not None:
        risk_rows = [r for r in risk_rows if r.get("stratum") == stratum]
        filing_rows = [f for f in filing_rows if f.get("stratum") == stratum]

    stale: list[str] = []
    if filings is not None:
        current = {f.accession_no: f.risk_digest for f in filings}
        for row in risk_rows:
            live = current.get(row["accession_no"])
            if live is not None and live != row["risk_digest"]:
                stale.append(row["id"])

    stale_ids = set(stale)
    reviewed = [
        r for r in risk_rows if r["id"] not in stale_ids and r.get("human_category") is not None
    ]

    by_filing: dict[str, list[dict]] = {}
    for row in reviewed:
        by_filing.setdefault(row["accession_no"], []).append(row)

    confusions: dict[tuple[str, str], int] = {}
    for row in reviewed:
        if row["human_category"] != row["teacher_category"]:
            key = (row["teacher_category"], row["human_category"])
            confusions[key] = confusions.get(key, 0) + 1

    read = [f for f in filing_rows if f.get("missed_risks") is not None]

    report = AuditReport(
        stratum=stratum,
        n_reviewed=len(reviewed),
        n_total=len(risk_rows),
        n_filings=len(by_filing),
        category_agreement=_rate([r["human_category"] == r["teacher_category"] for r in reviewed]),
        grounded_rate=_rate([bool(r["grounded"]) for r in reviewed if r["grounded"] is not None]),
        summary_ok_rate=_rate(
            [bool(r["summary_ok"]) for r in reviewed if r["summary_ok"] is not None]
        ),
        confusions=confusions,
        missed_risks=sum(f["missed_risks"] for f in read) if read else None,
        teacher_risks_in_read_filings=sum(f["n_teacher_risks"] for f in read),
        stale=stale,
    )
    report.cis = _bootstrap(by_filing, n_resamples=n_resamples, seed=seed)
    return report


def _bootstrap(
    by_filing: dict[str, list[dict]],
    n_resamples: int = BOOTSTRAP_RESAMPLES,
    confidence: float = BOOTSTRAP_CONFIDENCE,
    seed: int = DEFAULT_SEED,
) -> dict[str, ConfidenceInterval]:
    """Percentile bootstrap resampling **filings**, not items.

    The items are clustered: four risks drawn from one filing share a section, a reviewer's reading
    of it, and whatever the teacher misunderstood about that company. Resampling items would treat
    those four correlated outcomes as four independent ones and understate the interval.
    """
    clusters = list(by_filing.values())
    n = len(clusters)
    if n < MIN_CLUSTERS_FOR_CI or n_resamples <= 0:
        return {}

    draws: dict[str, list[float]] = {"category_agreement": [], "grounded_rate": [], "summary_ok_rate": []}
    rng = random.Random(seed)
    for _ in range(n_resamples):
        pooled = [row for _ in range(n) for row in clusters[rng.randrange(n)]]
        for key, values in (
            ("category_agreement", [r["human_category"] == r["teacher_category"] for r in pooled]),
            ("grounded_rate", [bool(r["grounded"]) for r in pooled if r["grounded"] is not None]),
            (
                "summary_ok_rate",
                [bool(r["summary_ok"]) for r in pooled if r["summary_ok"] is not None],
            ),
        ):
            rate = _rate(values)
            if rate is not None:
                draws[key].append(rate)

    tail = (1.0 - confidence) / 2.0
    out: dict[str, ConfidenceInterval] = {}
    for key, values in draws.items():
        if not values:
            continue
        values.sort()
        out[key] = ConfidenceInterval(
            low=_percentile(values, tail),
            high=_percentile(values, 1.0 - tail),
            confidence=confidence,
        )
    return out


_STRATUM_BLURB = {
    "random": "uniform draw over the corpus -- the unbiased label-quality estimate",
    "test": "oversampled test-split filings -- the gold labels the headline eval scores against",
}


def format_report(report: AuditReport) -> str:
    heading = "Teacher-label audit"
    if report.stratum:
        heading += f"  [{report.stratum} stratum: {_STRATUM_BLURB.get(report.stratum, '')}]"
    lines = ["", "=" * 68, heading]
    lines.append(
        f"  {report.n_reviewed} of {report.n_total} sampled risks reviewed, "
        f"across {report.n_filings} filing{'' if report.n_filings == 1 else 's'}"
    )
    if report.stale:
        lines.append(
            f"  {len(report.stale)} row(s) EXCLUDED as stale -- the labels changed since the sheet "
            "was drawn. Re-sample and re-review those filings."
        )
    if not report.n_reviewed:
        lines.append("\n  Nothing reviewed yet. Run `python -m src.labels.audit review`.")
        lines.append("=" * 68)
        return "\n".join(lines)

    lines.append("")
    for label, value, key in (
        ("Category agreement", report.category_agreement, "category_agreement"),
        ("Grounded in the text", report.grounded_rate, "grounded_rate"),
        ("Summary faithful", report.summary_ok_rate, "summary_ok_rate"),
    ):
        if value is None:
            continue
        ci = report.cis.get(key)
        interval = f"  95% CI {ci}" if ci else ""
        lines.append(f"  {label:22s} {value:6.1%}{interval}")
    if report.cis:
        lines.append("  Intervals are percentile bootstrap resampling filings, not items.")
    else:
        lines.append(
            f"  No intervals: {report.n_filings} reviewed filing(s) is under the "
            f"{MIN_CLUSTERS_FOR_CI}-cluster minimum, and a bootstrap over that few would report a "
            "point as if it were a range."
        )

    if report.confusions:
        lines.append("\nCategory disagreements (teacher -> human):")
        for (teacher, human), n in sorted(report.confusions.items(), key=lambda kv: -kv[1]):
            lines.append(f"  {teacher:22s} -> {human:22s} {n}")

    if report.missed_risks is not None:
        recall = report.implied_recall
        lines.append(
            f"\nRisks the teacher missed: {report.missed_risks} across "
            f"{report.teacher_risks_in_read_filings} labeled risks"
        )
        if recall is not None:
            lines.append(f"  implied recall (upper bound): {recall:.1%}")
    else:
        lines.append("\nNo filing-level recall recorded; missed-risk counts are unfilled.")

    lines.append("=" * 68)
    return "\n".join(lines)


# ------------------------------------------------------------------------------------------------
# Interactive review
# ------------------------------------------------------------------------------------------------


def _prompt_category() -> Optional[str]:
    """Blind category choice. Returns None if the reviewer wants to skip this item."""
    print("\n  Which category fits best?")
    for i, cat in enumerate(RISK_CATEGORIES, 1):
        print(f"    {i:2d}. {cat}")
    while True:
        raw = input("  number (or 's' to skip, 'q' to save and quit): ").strip().lower()
        if raw == "q":
            raise KeyboardInterrupt
        if raw == "s":
            return None
        if raw.isdigit() and 1 <= int(raw) <= len(RISK_CATEGORIES):
            return RISK_CATEGORIES[int(raw) - 1]
        print("  not a valid choice")


def _prompt_yes_no(question: str) -> bool:
    while True:
        raw = input(f"  {question} [y/n]: ").strip().lower()
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False
        if raw == "q":
            raise KeyboardInterrupt


def _prompt_int(question: str) -> Optional[int]:
    while True:
        raw = input(f"  {question} (integer, or 's' to skip): ").strip().lower()
        if raw == "s":
            return None
        if raw == "q":
            raise KeyboardInterrupt
        if raw.isdigit():
            return int(raw)


def review(sheet_path: Path = SHEET_PATH, filings_path: Path = FILINGS_PATH) -> None:
    """Walk the unreviewed rows, filing by filing. Saves after every item.

    Resumable by construction: an interrupted session leaves completed verdicts on disk, and the
    next run picks up at the first row whose `human_category` is still null. Auditing 50 risks is a
    couple of hours of reading; a flow that loses work on Ctrl-C would not get finished.
    """
    risk_rows = _read_jsonl(sheet_path)
    filing_rows = _read_jsonl(filings_path)
    filings = {f.accession_no: f for f in load_labeled_filings()}

    by_accession: dict[str, list[dict]] = {}
    for row in risk_rows:
        by_accession.setdefault(row["accession_no"], []).append(row)

    def save() -> None:
        _write_jsonl(sheet_path, risk_rows)
        _write_jsonl(filings_path, filing_rows)

    try:
        for filing_row in filing_rows:
            accession = filing_row["accession_no"]
            rows = by_accession.get(accession, [])
            pending = [r for r in rows if r["human_category"] is None]
            if not pending and filing_row["missed_risks"] is not None:
                continue

            filing = filings.get(accession)
            if filing is None:
                print(f"\n!! {accession} is no longer in the dataset; skipping.")
                continue

            print("\n" + "=" * 78)
            print(f"{filing_row['ticker']}  {accession}  ({filing_row['split']} split)")
            print(f"{filing_row['n_teacher_risks']} teacher labels, {len(pending)} to review here")
            print("=" * 78)
            input("Press Enter to print Item 1A (this is the exact text the teacher saw)...")
            print(filing.risk_text)

            for row in pending:
                print("\n" + "-" * 78)
                print(f"[{row['id']}]  {row['teacher_title']}")
                print(f"  summary: {row['teacher_summary']}")
                # The teacher's category is deliberately withheld until after the human commits.
                choice = _prompt_category()
                if choice is None:
                    continue
                row["human_category"] = choice
                verdict = "match" if choice == row["teacher_category"] else "DIFFERS"
                print(f"  teacher said: {row['teacher_category']}  ({verdict})")
                row["grounded"] = _prompt_yes_no("Is this risk actually stated in the text?")
                row["summary_ok"] = _prompt_yes_no("Is the summary faithful and company-specific?")
                row["note"] = input("  note (optional): ").strip()
                save()

            if filing_row["missed_risks"] is None:
                print("\n" + "-" * 78)
                missed = _prompt_int(
                    f"How many distinct risks did the teacher MISS in {filing_row['ticker']}?"
                )
                if missed is not None:
                    filing_row["missed_risks"] = missed
                    filing_row["note"] = input("  note (optional): ").strip()
                    save()
    except KeyboardInterrupt:
        save()
        print("\n\nSaved. Re-run `review` to continue where you left off.")
        return

    save()
    print("\nSheet complete. Run `python -m src.labels.audit score`.")


# ------------------------------------------------------------------------------------------------
# CLI
# ------------------------------------------------------------------------------------------------


def _cmd_sample(args: argparse.Namespace) -> None:
    if SHEET_PATH.exists() and not args.force:
        raise SystemExit(
            f"{SHEET_PATH} already exists. Re-sampling would discard the verdicts in it.\n"
            "Pass --force if that is what you want."
        )
    filings = load_labeled_filings()
    risk_rows, filing_rows = draw_sample(
        filings,
        n_filings=args.filings,
        per_filing=args.per_filing,
        seed=args.seed,
        test_filings=args.test_filings,
    )
    meta = {
        "seed": args.seed,
        "n_filings": args.filings,
        "per_filing": args.per_filing,
        "test_filings": args.test_filings,
        "population_filings": len(filings),
        "population_risks": sum(len(f.risks) for f in filings),
        "sampled_risks": len(risk_rows),
    }
    write_sheet(risk_rows, filing_rows, meta)
    print(
        f"Drew {len(risk_rows)} risks from {len(filing_rows)} filings "
        f"(population: {meta['population_risks']} risks in {meta['population_filings']} filings)."
    )
    for stratum in STRATA:
        rows = [f for f in filing_rows if f["stratum"] == stratum]
        if not rows:
            continue
        by_split = ", ".join(
            f"{sum(1 for r in rows if r['split'] == s)} {s}"
            for s in SPLITS
            if any(r["split"] == s for r in rows)
        )
        print(f"  {stratum:7s} {len(rows):2d} filings ({by_split})")
    print(f"\nWrote {SHEET_PATH.relative_to(ROOT)}")
    print("Next: python -m src.labels.audit review")


def _cmd_review(args: argparse.Namespace) -> None:
    review()


def _cmd_score(args: argparse.Namespace) -> None:
    risk_rows = _read_jsonl(SHEET_PATH)
    filing_rows = _read_jsonl(FILINGS_PATH)
    filings = load_labeled_filings()
    for stratum in STRATA:
        if not any(r.get("stratum") == stratum for r in risk_rows):
            continue
        report = score_sheet(
            risk_rows, filing_rows, filings=filings, seed=args.seed, stratum=stratum
        )
        print(format_report(report))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p_sample = sub.add_parser("sample", help="draw a review sheet")
    p_sample.add_argument("--filings", type=int, default=DEFAULT_FILINGS)
    p_sample.add_argument("--per-filing", type=int, default=DEFAULT_PER_FILING)
    p_sample.add_argument("--seed", type=int, default=DEFAULT_SEED)
    p_sample.add_argument(
        "--test-filings",
        type=int,
        default=DEFAULT_TEST_FILINGS,
        help="extra test-split filings, scored as a separate stratum (0 to disable)",
    )
    p_sample.add_argument("--force", action="store_true", help="overwrite an existing sheet")
    p_sample.set_defaults(func=_cmd_sample)

    p_review = sub.add_parser("review", help="fill in the sheet interactively")
    p_review.set_defaults(func=_cmd_review)

    p_score = sub.add_parser("score", help="agreement rates with clustered CIs")
    p_score.add_argument("--seed", type=int, default=DEFAULT_SEED)
    p_score.set_defaults(func=_cmd_score)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    sys.exit(main())
